<?php
$cards = array(
array("name"=>"Wild Boar","imageUrl"=>"cp011.jpg"),
array("name"=>"Black Adder","imageUrl"=>"cp012.jpg"),
array("name"=>"Red-Eyed Worg","imageUrl"=>"cp013.jpg"),
array("name"=>"Treetop Spider","imageUrl"=>"cp014.jpg"),
array("name"=>"Forest Serpent","imageUrl"=>"cp015.jpg"),
array("name"=>"Darkwood Panther","imageUrl"=>"cp016.jpg"),
array("name"=>"Cave Spider","imageUrl"=>"cp017.jpg"),
array("name"=>"Mountain Wolf","imageUrl"=>"cp018.jpg"),
array("name"=>"Great Bear","imageUrl"=>"cp019.jpg"),
array("name"=>"Caravan Smuggler","imageUrl"=>"cp020.jpg"),
array("name"=>"Eastroad Bandit","imageUrl"=>"cp021.jpg"),
array("name"=>"Winthill Assailer","imageUrl"=>"cp022.jpg"),
array("name"=>"Masked Bandit","imageUrl"=>"cp023.jpg"),
array("name"=>"Pillaging Arsonist","imageUrl"=>"cp024.jpg"),
array("name"=>"Brigand Captain","imageUrl"=>"cp025.jpg"),
array("name"=>"Twilight Herald","imageUrl"=>"ex001.jpg"),
array("name"=>"Gaderi Barbarian","imageUrl"=>"ex002.jpg"),
array("name"=>"Mystic of the Vale","imageUrl"=>"ex003.jpg"),
array("name"=>"Artful Squire","imageUrl"=>"ex004.jpg"),
array("name"=>"Braxnorian Soldier","imageUrl"=>"ex005.jpg"),
array("name"=>"Layarian Diplomat","imageUrl"=>"ex006.jpg"),
array("name"=>"Spirit Warden","imageUrl"=>"ex007.jpg"),
array("name"=>"Rider of Ellos","imageUrl"=>"ex008.jpg"),
array("name"=>"Fleet-footed Messenger","imageUrl"=>"ex009.jpg"),
array("name"=>"Radiant Wisp","imageUrl"=>"ex010.jpg"),
array("name"=>"Champion of Irum","imageUrl"=>"ex011.jpg"),
array("name"=>"Layarian Seductress","imageUrl"=>"ex012.jpg"),
array("name"=>"Paladin of Unaxio","imageUrl"=>"ex013.jpg"),
array("name"=>"Wymer the Lionheart","imageUrl"=>"ex014.jpg"),
array("name"=>"Gunther, General of Balor","imageUrl"=>"ex015.jpg"),
array("name"=>"Rotling","imageUrl"=>"ex016.jpg"),
array("name"=>"Twisted Familiar","imageUrl"=>"ex017.jpg"),
array("name"=>"Ironhide Karash","imageUrl"=>"ex018.jpg"),
array("name"=>"Bloodstained Marauder","imageUrl"=>"ex019.jpg"),
array("name"=>"Wulven Predator","imageUrl"=>"ex020.jpg"),
array("name"=>"Disciple of Aldmor","imageUrl"=>"ex021.jpg"),
array("name"=>"Rust Weevil","imageUrl"=>"ex022.jpg"),
array("name"=>"Magma Jackal","imageUrl"=>"ex023.jpg"),
array("name"=>"Morbid Acolyte","imageUrl"=>"ex024.jpg"),
array("name"=>"Darkwood Wraith","imageUrl"=>"ex025.jpg"),
array("name"=>"Death Collector","imageUrl"=>"ex026.jpg"),
array("name"=>"Wulven Savage","imageUrl"=>"ex027.jpg"),
array("name"=>"Furrion Terror","imageUrl"=>"ex028.jpg"),
array("name"=>"Io Void Leviathan","imageUrl"=>"ex029.jpg"),
array("name"=>"Kairos Doombringer","imageUrl"=>"ex030.jpg"),
array("name"=>"Alert and Able","imageUrl"=>"ex031.jpg"),
array("name"=>"Battle Hardened","imageUrl"=>"ex032.jpg"),
array("name"=>"Braxnorian Veteran","imageUrl"=>"ex033.jpg"),
array("name"=>"Lythite Coating","imageUrl"=>"ex034.jpg"),
array("name"=>"Smith Shop","imageUrl"=>"ex035.jpg"),
array("name"=>"Braxnorian Temptress","imageUrl"=>"ex036.jpg"),
array("name"=>"Killing Spree","imageUrl"=>"ex037.jpg"),
array("name"=>"Yari Spearman","imageUrl"=>"ex038.jpg"),
array("name"=>"Wild Berserker","imageUrl"=>"ex039.jpg"),
array("name"=>"Stalwart Battleguard","imageUrl"=>"ex040.jpg"),
array("name"=>"Scrying Eye","imageUrl"=>"ex041.jpg"),
array("name"=>"Kelvin's Charm","imageUrl"=>"ex042.jpg"),
array("name"=>"Meteor Shower","imageUrl"=>"ex043.jpg"),
array("name"=>"Undying Bond","imageUrl"=>"ex044.jpg"),
array("name"=>"Consuming Fear","imageUrl"=>"ex045.jpg"),
array("name"=>"Sun-blighted One","imageUrl"=>"ex046.jpg"),
array("name"=>"Static Shock","imageUrl"=>"ex047.jpg"),
array("name"=>"Voltar's Ring","imageUrl"=>"ex048.jpg"),
array("name"=>"Shatter Ice","imageUrl"=>"ex049.jpg"),
array("name"=>"Frosted Urigon","imageUrl"=>"ex050.jpg"),
array("name"=>"Rolling Boulders","imageUrl"=>"ex051.jpg"),
array("name"=>"Snare Trap","imageUrl"=>"ex052.jpg"),
array("name"=>"Bounty Hunter","imageUrl"=>"ex053.jpg"),
array("name"=>"Change of Plans","imageUrl"=>"ex054.jpg"),
array("name"=>"Survivalist","imageUrl"=>"ex055.jpg"),
array("name"=>"Enchanted Oak","imageUrl"=>"ex056.jpg"),
array("name"=>"Jade of the Forest","imageUrl"=>"ex057.jpg"),
array("name"=>"Wendith Eagle-eye","imageUrl"=>"ex058.jpg"),
array("name"=>"The Perfect Shot","imageUrl"=>"ex059.jpg"),
array("name"=>"Master Trapsetter","imageUrl"=>"ex060.jpg"),
array("name"=>"Sacred Fire Walker","imageUrl"=>"ex061.jpg"),
array("name"=>"Forgiveness","imageUrl"=>"ex062.jpg"),
array("name"=>"Devoted Lightbearer","imageUrl"=>"ex063.jpg"),
array("name"=>"Banish","imageUrl"=>"ex064.jpg"),
array("name"=>"Mass Purification","imageUrl"=>"ex065.jpg"),
array("name"=>"Incense of Atonement","imageUrl"=>"ex066.jpg"),
array("name"=>"Divine Connection","imageUrl"=>"ex067.jpg"),
array("name"=>"Lingering Essence","imageUrl"=>"ex068.jpg"),
array("name"=>"Elizabeth Winterborn","imageUrl"=>"ex069.jpg"),
array("name"=>"Knight of the Golden Dawn","imageUrl"=>"ex070.jpg"),
array("name"=>"Night Owl","imageUrl"=>"ex071.jpg"),
array("name"=>"Silent Strike","imageUrl"=>"ex072.jpg"),
array("name"=>"Elicit Information","imageUrl"=>"ex073.jpg"),
array("name"=>"Good Contacts","imageUrl"=>"ex074.jpg"),
array("name"=>"Vozitian Orders","imageUrl"=>"ex075.jpg"),
array("name"=>"Pay Day","imageUrl"=>"ex076.jpg"),
array("name"=>"Lyra Blackrose","imageUrl"=>"ex077.jpg"),
array("name"=>"Procured and Restored","imageUrl"=>"ex078.jpg"),
array("name"=>"Smoke Screen","imageUrl"=>"ex079.jpg"),
array("name"=>"Agent Rex","imageUrl"=>"ex080.jpg"),
array("name"=>"Blood Moon","imageUrl"=>"ex081.jpg"),
array("name"=>"Thick Hide","imageUrl"=>"ex082.jpg"),
array("name"=>"Ripping Fury","imageUrl"=>"ex083.jpg"),
array("name"=>"Lost in the Woods","imageUrl"=>"ex084.jpg"),
array("name"=>"Unstoppable","imageUrl"=>"ex085.jpg"),
array("name"=>"Tiger Wulf","imageUrl"=>"ex086.jpg"),
array("name"=>"Lightning Hunter","imageUrl"=>"ex087.jpg"),
array("name"=>"Call of the Pack","imageUrl"=>"ex088.jpg"),
array("name"=>"Blinding Storm","imageUrl"=>"ex089.jpg"),
array("name"=>"Howlfang, Terror of the Vale","imageUrl"=>"ex090.jpg"),
array("name"=>"Flare","imageUrl"=>"ex091.jpg"),
array("name"=>"Infinity Core","imageUrl"=>"ex092.jpg"),
array("name"=>"Synchronicity","imageUrl"=>"ex093.jpg"),
array("name"=>"Antimatter","imageUrl"=>"ex094.jpg"),
array("name"=>"Xar Modulator","imageUrl"=>"ex095.jpg"),
array("name"=>"Zantonite","imageUrl"=>"ex096.jpg"),
array("name"=>"Super Focus","imageUrl"=>"ex097.jpg"),
array("name"=>"Interference","imageUrl"=>"ex098.jpg"),
array("name"=>"Temporal Disturbance","imageUrl"=>"ex099.jpg"),
array("name"=>"Crystal Titan","imageUrl"=>"ex100.jpg"),
array("name"=>"Rejuvenating Ritual","imageUrl"=>"ex101.jpg"),
array("name"=>"Nurturing Spring","imageUrl"=>"ex102.jpg"),
array("name"=>"Nowhere To Hide","imageUrl"=>"ex103.jpg"),
array("name"=>"Disrupt Aura","imageUrl"=>"ex104.jpg"),
array("name"=>"Wizent's Prayer","imageUrl"=>"ex105.jpg"),
array("name"=>"Blessed Protection","imageUrl"=>"ex106.jpg"),
array("name"=>"Ascendant of the Hero","imageUrl"=>"ex107.jpg"),
array("name"=>"Outwitted","imageUrl"=>"ex108.jpg"),
array("name"=>"Treasured Heirloom","imageUrl"=>"ex109.jpg"),
array("name"=>"A Legend Rises","imageUrl"=>"ex110.jpg"),
array("name"=>"Mindless Ferocity","imageUrl"=>"ex111.jpg"),
array("name"=>"Contaminated Water","imageUrl"=>"ex112.jpg"),
array("name"=>"Nocturnal Advantage","imageUrl"=>"ex113.jpg"),
array("name"=>"Bloodthirsty","imageUrl"=>"ex114.jpg"),
array("name"=>"Aura of Retribution","imageUrl"=>"ex115.jpg"),
array("name"=>"Ascendant of the Horde","imageUrl"=>"ex116.jpg"),
array("name"=>"Arthyle's Crypt","imageUrl"=>"ex117.jpg"),
array("name"=>"Flesh Infusion","imageUrl"=>"ex118.jpg"),
array("name"=>"Blackened Heart","imageUrl"=>"ex119.jpg"),
array("name"=>"A Legend Falls","imageUrl"=>"ex120.jpg"),
array("name"=>"Word of the Prophet","imageUrl"=>"ex121.jpg"),
array("name"=>"Change of Fortune","imageUrl"=>"ex122.jpg"),
array("name"=>"Assumed Command","imageUrl"=>"ex123.jpg"),
array("name"=>"Sanctuary","imageUrl"=>"ex124.jpg"),
array("name"=>"Aldmor Conduit","imageUrl"=>"ex125.jpg"),
array("name"=>"Stand Firm","imageUrl"=>"ex126.jpg"),
array("name"=>"Toll Bridge","imageUrl"=>"ex127.jpg"),
array("name"=>"Dark Revelations","imageUrl"=>"ex128.jpg"),
array("name"=>"Thoughtful Investment","imageUrl"=>"ex129.jpg"),
array("name"=>"Scythe of Fate","imageUrl"=>"ex130.jpg"),
array("name"=>"Blazing Shield","imageUrl"=>"ex131.jpg"),
array("name"=>"Storm Coat","imageUrl"=>"ex132.jpg"),
array("name"=>"Punisher's Gauntlets","imageUrl"=>"ex133.jpg"),
array("name"=>"Breastplate of Vitality","imageUrl"=>"ex134.jpg"),
array("name"=>"Cloak of Obscurity","imageUrl"=>"ex135.jpg"),
array("name"=>"Morphic Armor","imageUrl"=>"ex136.jpg"),
array("name"=>"Pride of the Mountain","imageUrl"=>"ex137.jpg"),
array("name"=>"Celestial Armor","imageUrl"=>"ex138.jpg"),
array("name"=>"Rothem's Visage","imageUrl"=>"ex139.jpg"),
array("name"=>"Loest's Burden","imageUrl"=>"ex140.jpg"),
array("name"=>"Feathered Longbow","imageUrl"=>"ex141.jpg"),
array("name"=>"Staff of Disintegration","imageUrl"=>"ex142.jpg"),
array("name"=>"Wand of Izikus","imageUrl"=>"ex143.jpg"),
array("name"=>"Crescent of Doom","imageUrl"=>"ex144.jpg"),
array("name"=>"Grundler's Double","imageUrl"=>"ex145.jpg"),
array("name"=>"Dragon's Tooth","imageUrl"=>"ex146.jpg"),
array("name"=>"Shadowvein","imageUrl"=>"ex147.jpg"),
array("name"=>"Spectral Sabre","imageUrl"=>"ex148.jpg"),
array("name"=>"Madelain's Scepter","imageUrl"=>"ex149.jpg"),
array("name"=>"Fan of Blades","imageUrl"=>"ex150.jpg"),
array("name"=>"Karlstrad, Ruler of Gaderi","imageUrl"=>"ex151.jpg"),
array("name"=>"Scourge Colossus","imageUrl"=>"ex152.jpg"),
array("name"=>"Vigilant Wisp","imageUrl"=>"ll001.jpg"),
array("name"=>"Entangled Wisp","imageUrl"=>"ll002.jpg"),
array("name"=>"Unaxio Squire","imageUrl"=>"ll003.jpg"),
array("name"=>"Unaxio Bannerman","imageUrl"=>"ll004.jpg"),
array("name"=>"Sabreen, Hand of Unaxio","imageUrl"=>"ll005.jpg"),
array("name"=>"General of Unaxio","imageUrl"=>"ll006.jpg"),
array("name"=>"Twilight Shepherdess","imageUrl"=>"ll007.jpg"),
array("name"=>"Twilight Luminary","imageUrl"=>"ll008.jpg"),
array("name"=>"Twilight Orphic","imageUrl"=>"ll009.jpg"),
array("name"=>"Avatar of Twilight","imageUrl"=>"ll010.jpg"),
array("name"=>"Kallista, Twilight Matriarch","imageUrl"=>"ll011.jpg"),
array("name"=>"Flame Spitter","imageUrl"=>"ll016.jpg"),
array("name"=>"Sword Gobbler","imageUrl"=>"ll017.jpg"),
array("name"=>"Caged Savage","imageUrl"=>"ll018.jpg"),
array("name"=>"Feasterling","imageUrl"=>"ll019.jpg"),
array("name"=>"Towering Brute","imageUrl"=>"ll020.jpg"),
array("name"=>"Hellfire Besieger","imageUrl"=>"ll021.jpg"),
array("name"=>"Brakkong, Menace of Thriss","imageUrl"=>"ll022.jpg"),
array("name"=>"Kiruth Devotee","imageUrl"=>"ll023.jpg"),
array("name"=>"Forgotten Horror","imageUrl"=>"ll024.jpg"),
array("name"=>"Wulven Traitor","imageUrl"=>"ll025.jpg"),
array("name"=>"Wildfang, Wulven Renegade","imageUrl"=>"ll026.jpg"),
array("name"=>"Barrenland Gremlin","imageUrl"=>"ll031.jpg"),
array("name"=>"Eternal Troll","imageUrl"=>"ll032.jpg"),
array("name"=>"Armored Packbeast","imageUrl"=>"ll033.jpg"),
array("name"=>"Stalactitan","imageUrl"=>"ll034.jpg"),
array("name"=>"Void Wretch","imageUrl"=>"ll035.jpg"),
array("name"=>"Child of Aldmor","imageUrl"=>"ll036.jpg"),
array("name"=>"Aldmor Interceptor","imageUrl"=>"ll037.jpg"),
array("name"=>"Darklight Apprentice","imageUrl"=>"ll038.jpg"),
array("name"=>"Gloomwielder","imageUrl"=>"ll039.jpg"),
array("name"=>"Aldmor Artisan","imageUrl"=>"ll040.jpg"),
array("name"=>"Aldmor Scout","imageUrl"=>"ll041.jpg"),
array("name"=>"Aldmor Sentry","imageUrl"=>"ll042.jpg"),
array("name"=>"Aldmor Chieftan","imageUrl"=>"ll043.jpg"),
array("name"=>"Aldmor Scavenger","imageUrl"=>"ll044.jpg"),
array("name"=>"Ancient of Aldmor","imageUrl"=>"ll045.jpg"),
array("name"=>"Spirit of Devotion","imageUrl"=>"ll121.jpg"),
array("name"=>"Scriptures of the Departed","imageUrl"=>"ll122.jpg"),
array("name"=>"Moment of Acquiescence","imageUrl"=>"ll123.jpg"),
array("name"=>"Relentless Savagery","imageUrl"=>"ll131.jpg"),
array("name"=>"Tar-written Scroll","imageUrl"=>"ll132.jpg"),
array("name"=>"Thriss Crucible","imageUrl"=>"ll133.jpg"),
array("name"=>"Groundshift","imageUrl"=>"ll141.jpg"),
array("name"=>"Spontaneous Growth","imageUrl"=>"ll142.jpg"),
array("name"=>"Sinkhole","imageUrl"=>"ll143.jpg"),
array("name"=>"Rest for the Weary ","imageUrl"=>"ll144.jpg"),
array("name"=>"Clockwork Soldier","imageUrl"=>"ll145.jpg"),
array("name"=>"Disruptor Field","imageUrl"=>"ll146.jpg"),
array("name"=>"Rejuvenation Pod","imageUrl"=>"ll147.jpg"),
array("name"=>"Shadow Cannon","imageUrl"=>"ll148.jpg"),
array("name"=>"Aldmor Conflux","imageUrl"=>"ll149.jpg"),
array("name"=>"Lorhon: Twilight Encampment","imageUrl"=>"ll181.jpg"),
array("name"=>"Sosilo: Brothers' Landing","imageUrl"=>"ll182.jpg"),
array("name"=>"Anmor: Garina Road","imageUrl"=>"ll183.jpg"),
array("name"=>"Irum: Lightning Quarry","imageUrl"=>"ll184.jpg"),
array("name"=>"Gaderi: Braxno Citadel ","imageUrl"=>"ll186.jpg"),
array("name"=>"The Wilds: Trading Port","imageUrl"=>"ll187.jpg"),
array("name"=>"Racksul: Warped Desert","imageUrl"=>"ll188.jpg"),
array("name"=>"Arthyle's Pass: Dead Man's Breach","imageUrl"=>"ll189.jpg"),
array("name"=>"Yahari: Valley of Doom","imageUrl"=>"ll190.jpg"),
array("name"=>"Lyth: Kristan's Ridge","imageUrl"=>"ll191.jpg"),
array("name"=>"Ravenscrest: Valley of Secrets","imageUrl"=>"ll192.jpg"),
array("name"=>"Kiruth: Thaddeus' Vault","imageUrl"=>"ll196.jpg"),
array("name"=>"Asyn: Mount Kazarr","imageUrl"=>"ll197.jpg"),
array("name"=>"Lakmire: Training Outpost","imageUrl"=>"ll198.jpg"),
array("name"=>"Rankett: Proving Grounds","imageUrl"=>"ll199.jpg"),
array("name"=>"Boris Skullcrusher","imageUrl"=>"se001.jpg"),
array("name"=>"Amber Rain","imageUrl"=>"se002.jpg"),
array("name"=>"Victor Heartstriker","imageUrl"=>"se003.jpg"),
array("name"=>"Gwenneth Truesight","imageUrl"=>"se004.jpg"),
array("name"=>"Nishaven","imageUrl"=>"se005.jpg"),
array("name"=>"Eladwen Frostmire","imageUrl"=>"se006.jpg"),
array("name"=>"Jericho Spellbane","imageUrl"=>"se007.jpg"),
array("name"=>"Zhanna Mist","imageUrl"=>"se008.jpg"),
array("name"=>"Lance Shadowstalker","imageUrl"=>"se009.jpg"),
array("name"=>"Serena Thoughtripper","imageUrl"=>"se010.jpg"),
array("name"=>"Ter Adun","imageUrl"=>"se011.jpg"),
array("name"=>"Logan Stonebreaker","imageUrl"=>"se012.jpg"),
array("name"=>"Banebow","imageUrl"=>"se013.jpg"),
array("name"=>"Baduruu","imageUrl"=>"se014.jpg"),
array("name"=>"Majiya","imageUrl"=>"se015.jpg"),
array("name"=>"Gravebone","imageUrl"=>"se016.jpg"),
array("name"=>"Darkclaw","imageUrl"=>"se017.jpg"),
array("name"=>"Moonstalker","imageUrl"=>"se018.jpg"),
array("name"=>"Elementalis","imageUrl"=>"se019.jpg"),
array("name"=>"Zaladar","imageUrl"=>"se020.jpg"),
array("name"=>"Jasmine Rosecult","imageUrl"=>"se021.jpg"),
array("name"=>"Dirk Saber","imageUrl"=>"se022.jpg"),
array("name"=>"Sandra Trueblade","imageUrl"=>"se023.jpg"),
array("name"=>"Lily Rosecult","imageUrl"=>"se024.jpg"),
array("name"=>"Kristoffer Wyld","imageUrl"=>"se025.jpg"),
array("name"=>"Puwen Bloodhelm","imageUrl"=>"se026.jpg"),
array("name"=>"Birgitte Skullborn","imageUrl"=>"se027.jpg"),
array("name"=>"Kurt Whitehelm","imageUrl"=>"se028.jpg"),
array("name"=>"Erika Shadowhunter","imageUrl"=>"se029.jpg"),
array("name"=>"Blake Windrunner","imageUrl"=>"se030.jpg"),
array("name"=>"Raven Wildheart","imageUrl"=>"se031.jpg"),
array("name"=>"Aldon the Brave","imageUrl"=>"se032.jpg"),
array("name"=>"Zoe Silversmith","imageUrl"=>"se033.jpg"),
array("name"=>"Katrin the Shieldmaiden","imageUrl"=>"se034.jpg"),
array("name"=>"Priest of the Light","imageUrl"=>"se035.jpg"),
array("name"=>"Armored Sandworm","imageUrl"=>"se036.jpg"),
array("name"=>"Marshland Sentinel","imageUrl"=>"se037.jpg"),
array("name"=>"Tainted Oracle","imageUrl"=>"se038.jpg"),
array("name"=>"Earthen Protector","imageUrl"=>"se039.jpg"),
array("name"=>"Aeon Stormcaller","imageUrl"=>"se040.jpg"),
array("name"=>"Deathbone","imageUrl"=>"se041.jpg"),
array("name"=>"Keldor","imageUrl"=>"se042.jpg"),
array("name"=>"Infernal Gargoyle","imageUrl"=>"se043.jpg"),
array("name"=>"Brutalis","imageUrl"=>"se044.jpg"),
array("name"=>"Plasma Behemoth","imageUrl"=>"se045.jpg"),
array("name"=>"Chimera","imageUrl"=>"se046.jpg"),
array("name"=>"Fire Snake","imageUrl"=>"se047.jpg"),
array("name"=>"Belladonna","imageUrl"=>"se048.jpg"),
array("name"=>"Bad Wolf","imageUrl"=>"se049.jpg"),
array("name"=>"Medusil","imageUrl"=>"se050.jpg"),
array("name"=>"Hellsteed","imageUrl"=>"se051.jpg"),
array("name"=>"Dark Flayer","imageUrl"=>"se052.jpg"),
array("name"=>"Death Mage Thaddeus","imageUrl"=>"se053.jpg"),
array("name"=>"Carniboar","imageUrl"=>"se054.jpg"),
array("name"=>"Shadow Knight","imageUrl"=>"se055.jpg"),
array("name"=>"Cobra Demon","imageUrl"=>"se056.jpg"),
array("name"=>"Molten Destroyer","imageUrl"=>"se057.jpg"),
array("name"=>"Brutal Minotaur","imageUrl"=>"se058.jpg"),
array("name"=>"Wulven Tracker","imageUrl"=>"se059.jpg"),
array("name"=>"Ogloth the Glutton","imageUrl"=>"se060.jpg"),
array("name"=>"Valiant Defender","imageUrl"=>"se061.jpg"),
array("name"=>"Reserve Weapon","imageUrl"=>"se062.jpg"),
array("name"=>"War Banner","imageUrl"=>"se063.jpg"),
array("name"=>"Smashing Blow","imageUrl"=>"se064.jpg"),
array("name"=>"Enrage","imageUrl"=>"se065.jpg"),
array("name"=>"Warrior Training","imageUrl"=>"se066.jpg"),
array("name"=>"Crippling Blow","imageUrl"=>"se067.jpg"),
array("name"=>"Rampage","imageUrl"=>"se068.jpg"),
array("name"=>"Shield Bash","imageUrl"=>"se069.jpg"),
array("name"=>"Blood Frenzy","imageUrl"=>"se070.jpg"),
array("name"=>"Fireball","imageUrl"=>"se071.jpg"),
array("name"=>"Freezing Grip","imageUrl"=>"se072.jpg"),
array("name"=>"Poison Gas","imageUrl"=>"se073.jpg"),
array("name"=>"Lightning Strike","imageUrl"=>"se074.jpg"),
array("name"=>"Engulfing Flames","imageUrl"=>"se075.jpg"),
array("name"=>"Tome of Knowledge ","imageUrl"=>"se076.jpg"),
array("name"=>"Portal","imageUrl"=>"se077.jpg"),
array("name"=>"Supernova","imageUrl"=>"se078.jpg"),
array("name"=>"Arcane Burst","imageUrl"=>"se079.jpg"),
array("name"=>"Clinging Webs","imageUrl"=>"se080.jpg"),
array("name"=>"Aimed Shot","imageUrl"=>"se081.jpg"),
array("name"=>"Poison Arrow","imageUrl"=>"se082.jpg"),
array("name"=>"Flaming Arrow","imageUrl"=>"se083.jpg"),
array("name"=>"Rapid Fire","imageUrl"=>"se084.jpg"),
array("name"=>"Death Trap","imageUrl"=>"se085.jpg"),
array("name"=>"Into the Forest","imageUrl"=>"se086.jpg"),
array("name"=>"Battle Plans","imageUrl"=>"se087.jpg"),
array("name"=>"Surprise Attack","imageUrl"=>"se088.jpg"),
array("name"=>"Net Trap","imageUrl"=>"se089.jpg"),
array("name"=>"Tracking Gear","imageUrl"=>"se090.jpg"),
array("name"=>"Healing Touch","imageUrl"=>"se091.jpg"),
array("name"=>"Inner Strength","imageUrl"=>"se092.jpg"),
array("name"=>"Tidal Wave","imageUrl"=>"se093.jpg"),
array("name"=>"Ice Storm","imageUrl"=>"se094.jpg"),
array("name"=>"Focused Prayer","imageUrl"=>"se095.jpg"),
array("name"=>"Resurrection","imageUrl"=>"se096.jpg"),
array("name"=>"Holy Shield","imageUrl"=>"se097.jpg"),
array("name"=>"Plague","imageUrl"=>"se098.jpg"),
array("name"=>"Smite","imageUrl"=>"se099.jpg"),
array("name"=>"Book of Curses","imageUrl"=>"se100.jpg"),
array("name"=>"Assassination","imageUrl"=>"se101.jpg"),
array("name"=>"Reconnaissance","imageUrl"=>"se102.jpg"),
array("name"=>"Throwing Knife","imageUrl"=>"se103.jpg"),
array("name"=>"Sorcerous Poison","imageUrl"=>"se104.jpg"),
array("name"=>"Stop, Thief!","imageUrl"=>"se105.jpg"),
array("name"=>"Assassin's Cloak","imageUrl"=>"se106.jpg"),
array("name"=>"Ill-Gotten Gains","imageUrl"=>"se107.jpg"),
array("name"=>"Lay Low","imageUrl"=>"se108.jpg"),
array("name"=>"Mugged!","imageUrl"=>"se109.jpg"),
array("name"=>"Nightshade","imageUrl"=>"se110.jpg"),
array("name"=>"Captured Prey","imageUrl"=>"se111.jpg"),
array("name"=>"Pack Wolf","imageUrl"=>"se112.jpg"),
array("name"=>"Now You're Mine","imageUrl"=>"se113.jpg"),
array("name"=>"Speedstrike","imageUrl"=>"se114.jpg"),
array("name"=>"What Big Teeth","imageUrl"=>"se115.jpg"),
array("name"=>"Regeneration","imageUrl"=>"se116.jpg"),
array("name"=>"Full Moon","imageUrl"=>"se117.jpg"),
array("name"=>"Rabid Bite","imageUrl"=>"se118.jpg"),
array("name"=>"Lone Wolf","imageUrl"=>"se119.jpg"),
array("name"=>"Pack Alpha","imageUrl"=>"se120.jpg"),
array("name"=>"Energy Discharge","imageUrl"=>"se121.jpg"),
array("name"=>"Conversion","imageUrl"=>"se122.jpg"),
array("name"=>"Soul Reaper","imageUrl"=>"se123.jpg"),
array("name"=>"Spark","imageUrl"=>"se124.jpg"),
array("name"=>"Transference","imageUrl"=>"se125.jpg"),
array("name"=>"Mind Control","imageUrl"=>"se126.jpg"),
array("name"=>"Feedback","imageUrl"=>"se127.jpg"),
array("name"=>"Shard of Power","imageUrl"=>"se128.jpg"),
array("name"=>"Life Infusion","imageUrl"=>"se129.jpg"),
array("name"=>"Eternal Renewal","imageUrl"=>"se130.jpg"),
array("name"=>"Cover of Night","imageUrl"=>"se131.jpg"),
array("name"=>"Retreat!","imageUrl"=>"se132.jpg"),
array("name"=>"Reinforced Armor","imageUrl"=>"se133.jpg"),
array("name"=>"Special Delivery","imageUrl"=>"se134.jpg"),
array("name"=>"Campfire Stories","imageUrl"=>"se135.jpg"),
array("name"=>"Good Ascendant","imageUrl"=>"se136.jpg"),
array("name"=>"Radiant Sunlight","imageUrl"=>"se137.jpg"),
array("name"=>"Shrine of Negatia","imageUrl"=>"se138.jpg"),
array("name"=>"Poor Quality","imageUrl"=>"se139.jpg"),
array("name"=>"Honored Dead","imageUrl"=>"se140.jpg"),
array("name"=>"Bloodlust","imageUrl"=>"se141.jpg"),
array("name"=>"Here Be Monsters","imageUrl"=>"se142.jpg"),
array("name"=>"Shadowspawn","imageUrl"=>"se143.jpg"),
array("name"=>"Shriek of Vengeance","imageUrl"=>"se144.jpg"),
array("name"=>"Evil Ascendant","imageUrl"=>"se145.jpg"),
array("name"=>"Bloodstone Altar","imageUrl"=>"se146.jpg"),
array("name"=>"Selfishness","imageUrl"=>"se147.jpg"),
array("name"=>"Acid Jet","imageUrl"=>"se148.jpg"),
array("name"=>"Shadow Font","imageUrl"=>"se149.jpg"),
array("name"=>"Sacrificial Lamb","imageUrl"=>"se150.jpg"),
array("name"=>"Rain Delay","imageUrl"=>"se151.jpg"),
array("name"=>"Drain Power","imageUrl"=>"se152.jpg"),
array("name"=>"Urgent Business","imageUrl"=>"se153.jpg"),
array("name"=>"Extra Sharp","imageUrl"=>"se154.jpg"),
array("name"=>"Bazaar","imageUrl"=>"se155.jpg"),
array("name"=>"Sever Ties","imageUrl"=>"se156.jpg"),
array("name"=>"Bad Santa","imageUrl"=>"se157.jpg"),
array("name"=>"Master Smith","imageUrl"=>"se158.jpg"),
array("name"=>"Melt Down","imageUrl"=>"se159.jpg"),
array("name"=>"Ley Line Nexus","imageUrl"=>"se160.jpg"),
array("name"=>"Nova Infusion","imageUrl"=>"se161.jpg"),
array("name"=>"Snow Sapphire","imageUrl"=>"se162.jpg"),
array("name"=>"Violet Thunderstorm","imageUrl"=>"se163.jpg"),
array("name"=>"Armor of Ages","imageUrl"=>"se164.jpg"),
array("name"=>"The King's Pride","imageUrl"=>"se165.jpg"),
array("name"=>"Night Prowler","imageUrl"=>"se166.jpg"),
array("name"=>"Wrath of the Forest","imageUrl"=>"se167.jpg"),
array("name"=>"Crimson Vest","imageUrl"=>"se168.jpg"),
array("name"=>"Gravedigger's Cloak","imageUrl"=>"se169.jpg"),
array("name"=>"Cobraskin Wraps","imageUrl"=>"se170.jpg"),
array("name"=>"Black Garb","imageUrl"=>"se171.jpg"),
array("name"=>"Dome of Energy","imageUrl"=>"se172.jpg"),
array("name"=>"Plate Armor","imageUrl"=>"se173.jpg"),
array("name"=>"Moonlight Bracers","imageUrl"=>"se174.jpg"),
array("name"=>"Mocking Armor","imageUrl"=>"se175.jpg"),
array("name"=>"Legion United","imageUrl"=>"se176.jpg"),
array("name"=>"Twice Enchanted Robe","imageUrl"=>"se177.jpg"),
array("name"=>"Shadow Armor","imageUrl"=>"se178.jpg"),
array("name"=>"Crescendo","imageUrl"=>"se179.jpg"),
array("name"=>"Spelleater Bands","imageUrl"=>"se180.jpg"),
array("name"=>"Mournblade","imageUrl"=>"se181.jpg"),
array("name"=>"Dimension Ripper","imageUrl"=>"se182.jpg"),
array("name"=>"Berserker's Edge","imageUrl"=>"se183.jpg"),
array("name"=>"Jeweler's Dream","imageUrl"=>"se184.jpg"),
array("name"=>"Soul Seeker","imageUrl"=>"se185.jpg"),
array("name"=>"Guardian's Oath","imageUrl"=>"se186.jpg"),
array("name"=>"Beetle Demon Bow","imageUrl"=>"se187.jpg"),
array("name"=>"Rusty Longsword","imageUrl"=>"se188.jpg"),
array("name"=>"Wrath of Summer","imageUrl"=>"se189.jpg"),
array("name"=>"Voice of Winter","imageUrl"=>"se190.jpg"),
array("name"=>"Wooden Staff","imageUrl"=>"se191.jpg"),
array("name"=>"Sliver of Shadow","imageUrl"=>"se192.jpg"),
array("name"=>"Wizent's Staff","imageUrl"=>"se193.jpg"),
array("name"=>"Golden Katar","imageUrl"=>"se194.jpg"),
array("name"=>"Ghostmaker","imageUrl"=>"se195.jpg"),
array("name"=>"Old Iron Dagger","imageUrl"=>"se196.jpg"),
array("name"=>"Uprooted Tree","imageUrl"=>"se197.jpg"),
array("name"=>"Anklebreaker","imageUrl"=>"se198.jpg"),
array("name"=>"Fangs of the Predator","imageUrl"=>"se199.jpg"),
array("name"=>"Dagger of Unmaking","imageUrl"=>"se200.jpg"),
array("name"=>"Tala Pureheart","imageUrl"=>"sf001.jpg"),
array("name"=>"Aramia","imageUrl"=>"sf002.jpg"),
array("name"=>"Ythan Redthorn","imageUrl"=>"sf003.jpg"),
array("name"=>"Threbin the Righteous","imageUrl"=>"sf004.jpg"),
array("name"=>"Garth Ravensoul","imageUrl"=>"sf005.jpg"),
array("name"=>"Vess Swifthands","imageUrl"=>"sf006.jpg"),
array("name"=>"Raikka Spellseeker","imageUrl"=>"sf007.jpg"),
array("name"=>"Skervox","imageUrl"=>"sf008.jpg"),
array("name"=>"Bloodfang","imageUrl"=>"sf009.jpg"),
array("name"=>"Praxix","imageUrl"=>"sf010.jpg"),
array("name"=>"Ascetic of Aldmor","imageUrl"=>"sf011.jpg"),
array("name"=>"Aetherborn Wisp","imageUrl"=>"sf012.jpg"),
array("name"=>"Twilight Opportunist","imageUrl"=>"sf013.jpg"),
array("name"=>"Twilight Lifebringer","imageUrl"=>"sf014.jpg"),
array("name"=>"Zailen Crusader","imageUrl"=>"sf015.jpg"),
array("name"=>"Guardian of Unaxio","imageUrl"=>"sf016.jpg"),
array("name"=>"Midnight Sentinel","imageUrl"=>"sf017.jpg"),
array("name"=>"Sorcerer of Endia","imageUrl"=>"sf018.jpg"),
array("name"=>"Knight of Unaxio","imageUrl"=>"sf019.jpg"),
array("name"=>"Growing Bog-dweller","imageUrl"=>"sf020.jpg"),
array("name"=>"Eleanor, Princess of Ellos","imageUrl"=>"sf021.jpg"),
array("name"=>"Zealous Mystic","imageUrl"=>"sf022.jpg"),
array("name"=>"Demetreyo, Twilight Extremist","imageUrl"=>"sf023.jpg"),
array("name"=>"Twilight Ritualist","imageUrl"=>"sf024.jpg"),
array("name"=>"Twilight Warden","imageUrl"=>"sf025.jpg"),
array("name"=>"Twilight Champion","imageUrl"=>"sf026.jpg"),
array("name"=>"Templar Champion","imageUrl"=>"sf027.jpg"),
array("name"=>"Viska, The Scarlet Blade","imageUrl"=>"sf028.jpg"),
array("name"=>"Avenger of the Fallen","imageUrl"=>"sf029.jpg"),
array("name"=>"Tenacious Buccaneer","imageUrl"=>"sf030.jpg"),
array("name"=>"Irina, Guardian of the Swan","imageUrl"=>"sf031.jpg"),
array("name"=>"Fortified Wisp","imageUrl"=>"sf032.jpg"),
array("name"=>"Thunderstrike Construct","imageUrl"=>"sf033.jpg"),
array("name"=>"Eriss Fateweaver","imageUrl"=>"sf034.jpg"),
array("name"=>"Nathanias, People's Champion","imageUrl"=>"sf035.jpg"),
array("name"=>"Plightbred Runt","imageUrl"=>"sf036.jpg"),
array("name"=>"Rapacious Vermin","imageUrl"=>"sf037.jpg"),
array("name"=>"Frostmare","imageUrl"=>"sf038.jpg"),
array("name"=>"Harbinger of the Lost","imageUrl"=>"sf039.jpg"),
array("name"=>"Spitfire Hound","imageUrl"=>"sf040.jpg"),
array("name"=>"Wulven Scout","imageUrl"=>"sf041.jpg"),
array("name"=>"Cleric of the Asyn","imageUrl"=>"sf042.jpg"),
array("name"=>"Cryptspawn Tormentor","imageUrl"=>"sf043.jpg"),
array("name"=>"Gravemonger","imageUrl"=>"sf044.jpg"),
array("name"=>"Wulven Tactician","imageUrl"=>"sf045.jpg"),
array("name"=>"Rampant Krygon","imageUrl"=>"sf046.jpg"),
array("name"=>"Ravager Zealot","imageUrl"=>"sf047.jpg"),
array("name"=>"Grimghast","imageUrl"=>"sf048.jpg"),
array("name"=>"Voracious Arachnid","imageUrl"=>"sf049.jpg"),
array("name"=>"Corpse Shifter","imageUrl"=>"sf050.jpg"),
array("name"=>"Murderous Hulk","imageUrl"=>"sf051.jpg"),
array("name"=>"Grimjaw Hydra","imageUrl"=>"sf052.jpg"),
array("name"=>"Flameborn Defiler","imageUrl"=>"sf053.jpg"),
array("name"=>"Brimstone Devourer","imageUrl"=>"sf054.jpg"),
array("name"=>"Slingblade Demon","imageUrl"=>"sf055.jpg"),
array("name"=>"Falseblood Cultist","imageUrl"=>"sf056.jpg"),
array("name"=>"Thriss Demolitionist","imageUrl"=>"sf057.jpg"),
array("name"=>"Der'kan, the Bone King","imageUrl"=>"sf058.jpg"),
array("name"=>"Infernus, Tyrant of the Damned","imageUrl"=>"sf059.jpg"),
array("name"=>"Dakrath","imageUrl"=>"sf060.jpg"),
array("name"=>"Lythian Shackles","imageUrl"=>"sf061.jpg"),
array("name"=>"Crown of Ages","imageUrl"=>"sf062.jpg"),
array("name"=>"Ellos' Resolve","imageUrl"=>"sf063.jpg"),
array("name"=>"Yari Vanguard","imageUrl"=>"sf064.jpg"),
array("name"=>"Mettle of the Warrior","imageUrl"=>"sf065.jpg"),
array("name"=>"Yari Marksman","imageUrl"=>"sf066.jpg"),
array("name"=>"Yari Bladedancer","imageUrl"=>"sf067.jpg"),
array("name"=>"Desperate Tactics","imageUrl"=>"sf068.jpg"),
array("name"=>"Enslave the Beast","imageUrl"=>"sf069.jpg"),
array("name"=>"Xander, Yari Captain","imageUrl"=>"sf070.jpg"),
array("name"=>"Abomination Factory","imageUrl"=>"sf071.jpg"),
array("name"=>"Stoneskin","imageUrl"=>"sf072.jpg"),
array("name"=>"Cinderborn Fatebreaker","imageUrl"=>"sf073.jpg"),
array("name"=>"Amulet of Conjuring","imageUrl"=>"sf074.jpg"),
array("name"=>"Incendiary Curse","imageUrl"=>"sf075.jpg"),
array("name"=>"Thunderstone Golem","imageUrl"=>"sf076.jpg"),
array("name"=>"Urigon's Fang","imageUrl"=>"sf077.jpg"),
array("name"=>"Evolving Abomination","imageUrl"=>"sf078.jpg"),
array("name"=>"Transmogrification Curse","imageUrl"=>"sf079.jpg"),
array("name"=>"Phoenix Urigon","imageUrl"=>"sf080.jpg"),
array("name"=>"Pack an Extra","imageUrl"=>"sf081.jpg"),
array("name"=>"Anmor's Elixir","imageUrl"=>"sf082.jpg"),
array("name"=>"Ricochet Trap","imageUrl"=>"sf083.jpg"),
array("name"=>"Hunter's Gambit","imageUrl"=>"sf084.jpg"),
array("name"=>"Venomflame Archer","imageUrl"=>"sf085.jpg"),
array("name"=>"Deepwood Bobcat","imageUrl"=>"sf086.jpg"),
array("name"=>"Decoy Trap","imageUrl"=>"sf087.jpg"),
array("name"=>"Anmor's Call","imageUrl"=>"sf088.jpg"),
array("name"=>"Snowland Spotter","imageUrl"=>"sf089.jpg"),
array("name"=>"Drangis, Lord of the Hunt","imageUrl"=>"sf090.jpg"),
array("name"=>"For Unaxio!","imageUrl"=>"sf091.jpg"),
array("name"=>"Tome of Blessings","imageUrl"=>"sf092.jpg"),
array("name"=>"Glass Chalice of Knowing","imageUrl"=>"sf093.jpg"),
array("name"=>"Embers of the Just","imageUrl"=>"sf094.jpg"),
array("name"=>"Devoted Knight","imageUrl"=>"sf095.jpg"),
array("name"=>"Righteous Strike","imageUrl"=>"sf096.jpg"),
array("name"=>"Arada Jewels","imageUrl"=>"sf097.jpg"),
array("name"=>"Sindarok Apprentice","imageUrl"=>"sf098.jpg"),
array("name"=>"Zail's Hymn","imageUrl"=>"sf099.jpg"),
array("name"=>"Justicar Alysia","imageUrl"=>"sf100.jpg"),
array("name"=>"Skilled Ironmonger","imageUrl"=>"sf101.jpg"),
array("name"=>"Backstab","imageUrl"=>"sf102.jpg"),
array("name"=>"Hit List","imageUrl"=>"sf103.jpg"),
array("name"=>"Vozitian Trader","imageUrl"=>"sf104.jpg"),
array("name"=>"Wily Smuggler","imageUrl"=>"sf105.jpg"),
array("name"=>"Garth's Concoction","imageUrl"=>"sf106.jpg"),
array("name"=>"Sword Thief","imageUrl"=>"sf107.jpg"),
array("name"=>"Coercion","imageUrl"=>"sf108.jpg"),
array("name"=>"Anarchic Looting","imageUrl"=>"sf109.jpg"),
array("name"=>"Oliver Fagin","imageUrl"=>"sf110.jpg"),
array("name"=>"Midnight Howl","imageUrl"=>"sf111.jpg"),
array("name"=>"Bloodpack Shaman","imageUrl"=>"sf112.jpg"),
array("name"=>"Death from Above","imageUrl"=>"sf113.jpg"),
array("name"=>"Wulven Rally","imageUrl"=>"sf114.jpg"),
array("name"=>"Dreadclaw Totem","imageUrl"=>"sf115.jpg"),
array("name"=>"Dread Wolf","imageUrl"=>"sf116.jpg"),
array("name"=>"Wulven Resilience","imageUrl"=>"sf117.jpg"),
array("name"=>"Soothjaw","imageUrl"=>"sf118.jpg"),
array("name"=>"Griptooth","imageUrl"=>"sf119.jpg"),
array("name"=>"Riphide","imageUrl"=>"sf120.jpg"),
array("name"=>"Shocking Grasp","imageUrl"=>"sf121.jpg"),
array("name"=>"Redux Channel","imageUrl"=>"sf122.jpg"),
array("name"=>"Reverberate","imageUrl"=>"sf123.jpg"),
array("name"=>"Energy Extraction","imageUrl"=>"sf124.jpg"),
array("name"=>"Wave Collapse","imageUrl"=>"sf125.jpg"),
array("name"=>"Stardust Extractor","imageUrl"=>"sf126.jpg"),
array("name"=>"Mimic","imageUrl"=>"sf127.jpg"),
array("name"=>"Reactorary","imageUrl"=>"sf128.jpg"),
array("name"=>"Exaltation","imageUrl"=>"sf129.jpg"),
array("name"=>"Stardust Ampliflyer","imageUrl"=>"sf130.jpg"),
array("name"=>"Final Flourish","imageUrl"=>"sf131.jpg"),
array("name"=>"Strength of Conviction","imageUrl"=>"sf132.jpg"),
array("name"=>"Twilight Eidolon","imageUrl"=>"sf133.jpg"),
array("name"=>"Scriptures of the Righteous","imageUrl"=>"sf134.jpg"),
array("name"=>"Saymeht's Retribution","imageUrl"=>"sf135.jpg"),
array("name"=>"The Bigger They Are","imageUrl"=>"sf136.jpg"),
array("name"=>"Road Less Traveled","imageUrl"=>"sf137.jpg"),
array("name"=>"Live Together, Die Alone","imageUrl"=>"sf138.jpg"),
array("name"=>"The Last Harvest","imageUrl"=>"sf139.jpg"),
array("name"=>"Glimmer of Hope","imageUrl"=>"sf140.jpg"),
array("name"=>"Grave Resistance","imageUrl"=>"sf141.jpg"),
array("name"=>"Thriss Assault Plinth","imageUrl"=>"sf142.jpg"),
array("name"=>"Despair","imageUrl"=>"sf143.jpg"),
array("name"=>"Tombstone Beacon","imageUrl"=>"sf144.jpg"),
array("name"=>"Shriek of Revulsion","imageUrl"=>"sf145.jpg"),
array("name"=>"The Harder They Fall","imageUrl"=>"sf146.jpg"),
array("name"=>"Mark of the Feared","imageUrl"=>"sf147.jpg"),
array("name"=>"Obelisk of Echoes","imageUrl"=>"sf148.jpg"),
array("name"=>"Meat Wagon","imageUrl"=>"sf149.jpg"),
array("name"=>"All Hope is Lost","imageUrl"=>"sf150.jpg"),
array("name"=>"Loom of Fate","imageUrl"=>"sf151.jpg"),
array("name"=>"Crystal Shards","imageUrl"=>"sf152.jpg"),
array("name"=>"Curse of the Aldmor","imageUrl"=>"sf153.jpg"),
array("name"=>"Vision of Endia","imageUrl"=>"sf154.jpg"),
array("name"=>"Overwhelm","imageUrl"=>"sf155.jpg"),
array("name"=>"Dawn Raid","imageUrl"=>"sf156.jpg"),
array("name"=>"Will to Fight","imageUrl"=>"sf157.jpg"),
array("name"=>"Widespread Decay","imageUrl"=>"sf158.jpg"),
array("name"=>"Aldmor Accelerator","imageUrl"=>"sf159.jpg"),
array("name"=>"Confluence of Fate","imageUrl"=>"sf160.jpg"),
array("name"=>"Startleshell Vest","imageUrl"=>"sf161.jpg"),
array("name"=>"Platinum Chainmail","imageUrl"=>"sf162.jpg"),
array("name"=>"Gold-Laced Shield","imageUrl"=>"sf163.jpg"),
array("name"=>"Helm of Saymeht","imageUrl"=>"sf164.jpg"),
array("name"=>"Ritualist's Headdress","imageUrl"=>"sf165.jpg"),
array("name"=>"Splicer's Crown","imageUrl"=>"sf166.jpg"),
array("name"=>"Cleric's Mantle","imageUrl"=>"sf167.jpg"),
array("name"=>"Necromancer's Shroud","imageUrl"=>"sf168.jpg"),
array("name"=>"Justicar's Cape","imageUrl"=>"sf169.jpg"),
array("name"=>"Pride of the Yari","imageUrl"=>"sf170.jpg"),
array("name"=>"Shock Conductor","imageUrl"=>"sf171.jpg"),
array("name"=>"Flameforged Gauntlets","imageUrl"=>"sf172.jpg"),
array("name"=>"Aural Battery","imageUrl"=>"sf173.jpg"),
array("name"=>"Packmaster's Helm","imageUrl"=>"sf174.jpg"),
array("name"=>"Rilard's Buckler","imageUrl"=>"sf175.jpg"),
array("name"=>"Metamorphic Cloak","imageUrl"=>"sf176.jpg"),
array("name"=>"Robes of Mending","imageUrl"=>"sf177.jpg"),
array("name"=>"Soulbound Armor","imageUrl"=>"sf178.jpg"),
array("name"=>"Voidwalker's Gauntlet","imageUrl"=>"sf179.jpg"),
array("name"=>"Charred Cowl of the Damned","imageUrl"=>"sf180.jpg"),
array("name"=>"Frying Pan","imageUrl"=>"sf181.jpg"),
array("name"=>"Boooomerang","imageUrl"=>"sf182.jpg"),
array("name"=>"Wooden Spear","imageUrl"=>"sf183.jpg"),
array("name"=>"Griffoncrest Dagger","imageUrl"=>"sf184.jpg"),
array("name"=>"Sword of Might","imageUrl"=>"sf185.jpg"),
array("name"=>"Looter's Baton","imageUrl"=>"sf186.jpg"),
array("name"=>"Dagger of Fate","imageUrl"=>"sf187.jpg"),
array("name"=>"Weevil-tipped Crossbow","imageUrl"=>"sf188.jpg"),
array("name"=>"Pithing Spear","imageUrl"=>"sf189.jpg"),
array("name"=>"Rod of Smiting","imageUrl"=>"sf190.jpg"),
array("name"=>"Darkforged Knife","imageUrl"=>"sf191.jpg"),
array("name"=>"Bone Sabre","imageUrl"=>"sf192.jpg"),
array("name"=>"War Flail","imageUrl"=>"sf193.jpg"),
array("name"=>"Gromm's Axe","imageUrl"=>"sf194.jpg"),
array("name"=>"Thoughtripper's Cutlass","imageUrl"=>"sf195.jpg"),
array("name"=>"Chains of Torment","imageUrl"=>"sf196.jpg"),
array("name"=>"Spirit Shuriken","imageUrl"=>"sf197.jpg"),
array("name"=>"Flameforged Scepter","imageUrl"=>"sf198.jpg"),
array("name"=>"Lythian Sledgehammer","imageUrl"=>"sf199.jpg"),
array("name"=>"Emore Crossbow","imageUrl"=>"sf200.jpg"),
array("name"=>"Loest, Savior of Layar","imageUrl"=>"sf201.jpg"),
array("name"=>"Rothem, King of Layar","imageUrl"=>"sf202.jpg")
);
return $cards;
?>